[phases.setup]
nixpkgs.archive = "nixpkgs:unstable"
nixpkgs.pkgs = ["go_1_22"]

[phases.build]
cmds = ["go build -trimpath -ldflags='-s -w' -o /build/output/dys ./cmd/dys"]

[start]
cmd = "/build/output/dys"
